apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: assessment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-nginx
          mountPath: /etc/nginx
      volumes:
        - name: config-nginx
          configMap:
            name: config-nginx
